### ISSUE TITLE
Add bot name to .env file

### ISSUE THREAD

**Issue by brooksbecton** [brooksbecton/ItsWednesdayMyDudesDiscordBot#8]
If you don't change the if statement in the ['checkIfWednesday' middleware](https://github.com/brooksbecton/ItsWednesdayMyDudesDiscordBot/blob/develop/middleware/checkIfWednesday/index.js#L5) from the prod username to your test username, the bot tends to hear itself and then falls into a loop hearing "wednesday" and "my dude"  from itself then replying then rinse and repeat. 

Adding the bot name to the env file will make testing easier and since you already have to enter your own token for testing the bot locally, it would be easy to add in your bot's name in the .env file too

- [x] Add environment variable to env
- [x] Change [hard coded username](https://github.com/brooksbecton/ItsWednesdayMyDudesDiscordBot/blob/develop/middleware/checkIfWednesday/index.js#L5)
- [x] Update [Setup Section](https://github.com/brooksbecton/ItsWednesdayMyDudesDiscordBot#setup)
- [x] Update [.env.example file](https://github.com/brooksbecton/ItsWednesdayMyDudesDiscordBot/blob/develop/.env.example)

**Comment by AlexMolbert** [comment]
Dibs

**Comment by brooksbecton** [comment]
Handled in #9
